spring.application.name=FeedBackProject
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/acetcse
spring.datasource.username=root
spring.datasource.password=Satya2356
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

upload.path=uploads/

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
logging.level.root=INFO
logging.level.com.example.feedback=DEBUG
logging.file.name=logs/faculty-feedback.log
